name: upgrade nodes on test env

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  upgrade_nodes_on_test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Define docker image tag
      run: echo "DOCKER_IMAGE_TAG=omerfirmak-5670d77fe656667141be980916f908db17c832a8" >> $GITHUB_ENV

    - name: Remove old Juno containers and start new ones
      uses: appleboy/ssh-action@v0.1.8
      env:
        DOCKER_IMAGE: ${{ env.DOCKER_IMAGE_TAG }}
        HOST: ${{ github.event_name == 'push' && secrets.STAGING_IP || github.event_name == 'release' && secrets.RELEASE_IP }}
      with:
        host: ${{ env.HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        envs: DOCKER_IMAGE
        script: |
            port=6060
            for network in mainnet goerli goerli2; do
                docker stop juno_$network
                docker rm juno_$network
                docker run -d \
                    --name juno_$network \
                    -p $port:6060 \
                    -v /root/juno_$network:/var/lib/juno \
                    nethermindeth/juno:$DOCKER_IMAGE \
                    --db-path /var/lib/juno \
                    --rpc-port 6060 \
                    --network $network \
                    --colour=false \
                    $(if [ "$network" = "mainnet" ]; then echo "--pprof"; fi)
                port=$((port+1))
                nohup sh -c "docker logs -f juno_$network > /var/log/juno_logs_$network.log" &>/dev/null &
            done
            